---
sensitiveCodepaths:
  - 'streams.js'
  - 'index.html'
allowedAuthors:
  usernames:
    - jetrom17
codePolicies:
  - title: "XSS attack index.html"
    question: "Ways to prevent XSS attacks?"
---
